import {useEffect,useState} from "react";import {api,resetCsrf} from "./lib/api.js";
type User={id:number;email:string;role:"owner"|"admin"};const input="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 outline-none focus:border-emerald-500";
function Card({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5 shadow-xl">{children}</div>}
function Login({onLogin}:{onLogin:(u:User)=>void}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})});onLogin(r.user)}catch(e){setError(e instanceof Error?e.message:"Login failed")}finally{setBusy(false)}};return <main className="flex min-h-screen items-center justify-center bg-zinc-950 p-4"><Card><div className="w-full max-w-sm"><p className="text-sm font-semibold text-emerald-400">MC PANEL</p><h1 className="mt-2 text-2xl font-bold">Sign in</h1><p className="mt-2 text-sm text-zinc-400">Private server management access.</p><form onSubmit={submit} className="mt-6 space-y-4"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className={input}/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" className={input}/>{error&&<p className="text-sm text-red-400">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-emerald-500 px-4 py-3 font-semibold text-zinc-950 disabled:opacity-50">{busy?"Signing in…":"Sign in"}</button></form><a href="/setup" className="mt-5 block text-center text-sm text-zinc-400">First-time setup</a></div></Card></main>}
function Setup({onLogin}:{onLogin:(u:User)=>void}){const[token,setToken]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await api("/api/auth/setup",{method:"POST",body:JSON.stringify({setupToken:token,email,password})});onLogin(r.user);history.replaceState(null,"","/")}catch(e){setError(e instanceof Error?e.message:"Setup failed")}finally{setBusy(false)}};return <main className="flex min-h-screen items-center justify-center bg-zinc-950 p-4"><Card><div className="w-full max-w-sm"><p className="text-sm font-semibold text-emerald-400">MC PANEL SETUP</p><h1 className="mt-2 text-2xl font-bold">Create owner</h1><p className="mt-2 text-sm text-zinc-400">Paste the one-time token printed once in the server log.</p><form onSubmit={submit} className="mt-6 space-y-4"><input required value={token} onChange={e=>setToken(e.target.value)} placeholder="Setup token" className={input+" font-mono text-sm"}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Owner email" className={input}/><input required minLength={12} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (12+ characters)" className={input}/>{error&&<p className="text-sm text-red-400">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-emerald-500 px-4 py-3 font-semibold text-zinc-950">{busy?"Creating…":"Create owner"}</button></form><a href="/login" className="mt-5 block text-center text-sm text-zinc-400">Back to login</a></div></Card></main>}
function ChangePassword({user,onLogout}:{user:User;onLogout:()=>void}){const[currentPassword,setCurrent]=useState(""),[newPassword,setNew]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");setError("");try{await api("/api/auth/change-password",{method:"POST",body:JSON.stringify({currentPassword,newPassword})});resetCsrf();setMessage("Password changed. All sessions were revoked; sign in again.");setTimeout(onLogout,800)}catch(e){setError(e instanceof Error?e.message:"Unable to change password")}};return <main className="min-h-screen bg-zinc-950 p-4 text-zinc-100"><div className="mx-auto max-w-lg pt-10"><Card><p className="text-sm text-emerald-400">ACCOUNT</p><h1 className="mt-2 text-2xl font-bold">Change password</h1><p className="mt-2 text-sm text-zinc-400">{user.email}</p><form onSubmit={submit} className="mt-6 space-y-4"><input required type="password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} placeholder="Current password" className={input}/><input required minLength={12} type="password" value={newPassword} onChange={e=>setNew(e.target.value)} placeholder="New password (12+ characters)" className={input}/>{message&&<p className="text-sm text-emerald-400">{message}</p>}{error&&<p className="text-sm text-red-400">{error}</p>}<button className="w-full rounded-xl bg-emerald-500 px-4 py-3 font-semibold text-zinc-950">Change password</button></form></Card></div></main>}
function Dashboard({user,onLogout}:{user:User;onLogout:()=>void}){const[type,setType]=useState("paper"),[version,setVersion]=useState(""),[versions,setVersions]=useState<{id:string}[]>([]),[status,setStatus]=useState({status:"offline",pid:null as number|null}),[java,setJava]=useState<{path:string;major:number;version:string}[]>([]),[min,setMin]=useState("1024"),[max,setMax]=useState("4096"),[eula,setEula]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");
const load=async(t:string)=>{try{const r=await api("/api/versions?type="+encodeURIComponent(t));setVersions(r.versions);if(r.versions[0])setVersion(r.versions[0].id)}catch(e){setError(e instanceof Error?e.message:"Unable to load versions")}};
const refresh=async()=>{try{setStatus(await api("/api/server/status"));const c=await api("/api/versions/config");setMin(String(c.minRamMb));setMax(String(c.maxRamMb));setEula(Boolean(c.eulaAcceptedAt));setJava((await api("/api/versions/java")).java)}catch(e){setError(e instanceof Error?e.message:"Unable to load state")}};
useEffect(()=>{void load(type);void refresh();const timer=setInterval(()=>void refresh(),3000);return()=>clearInterval(timer)},[]);
const action=async(path:string)=>{try{await api(path,{method:"POST"});await refresh()}catch(e){setError(e instanceof Error?e.message:"Action failed")}};
const install=async()=>{try{const r=await api("/api/versions/install",{method:"POST",body:JSON.stringify({type,version})});setMsg("Installed "+r.type+" "+r.version+". Accept the EULA before starting.");setEula(false);await refresh()}catch(e){setError(e instanceof Error?e.message:"Install failed")}};
const saveRam=async()=>{try{await api("/api/versions/ram",{method:"POST",body:JSON.stringify({minRamMb:Number(min),maxRamMb:Number(max)})});setMsg("RAM saved.")}catch(e){setError(e instanceof Error?e.message:"RAM update failed")}};
const accept=async()=>{try{await api("/api/versions/eula",{method:"POST",body:JSON.stringify({accepted:true})});setEula(true);setMsg("EULA accepted.")}catch(e){setError(e instanceof Error?e.message:"EULA update failed")}};
const logout=async()=>{try{await api("/api/auth/logout",{method:"POST"})}finally{resetCsrf();onLogout();history.replaceState(null,"","/login")}};
return <main className="min-h-screen bg-zinc-950 p-4 text-zinc-100"><div className="mx-auto max-w-5xl pt-6 space-y-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-emerald-400">MC PANEL</p><h1 className="text-3xl font-bold">Server Dashboard</h1><p className="text-sm text-zinc-400">{user.email} · {user.role}</p></div><button onClick={logout} className="rounded-xl bg-zinc-800 px-4 py-2 text-sm">Logout</button></header>
<Card><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-zinc-400">Status</p><p className="text-xl font-semibold">{status.status}{status.pid?" · PID "+status.pid:""}</p></div><div className="flex flex-wrap gap-2">{["start","stop","restart","kill"].map(x=><button key={x} onClick={()=>action("/api/server/"+x)} className="rounded-xl border border-zinc-700 px-3 py-2 text-sm">{x}</button>)}</div></div></Card>
<div className="grid gap-6 md:grid-cols-2"><Card><h2 className="text-lg font-semibold">Server installation</h2><div className="mt-4 space-y-3"><select value={type} onChange={e=>{setType(e.target.value);void load(e.target.value)}} className={input}><option value="vanilla">Vanilla</option><option value="paper">Paper</option><option value="fabric">Fabric</option><option value="forge">Forge</option></select><select value={version} onChange={e=>setVersion(e.target.value)} className={input}>{versions.map(v=><option key={v.id}>{v.id}</option>)}</select><button disabled={!version||status.status!=="offline"} onClick={install} className="w-full rounded-xl bg-emerald-500 px-4 py-3 font-semibold text-zinc-950 disabled:opacity-40">Install selected version</button></div></Card>
<Card><h2 className="text-lg font-semibold">Java & RAM</h2><p className="mt-2 text-sm text-zinc-400">{java.length?java.map(j=>"Java "+j.major+" ("+j.version+")").join(", "):"No Java runtimes detected"}</p><div className="mt-4 grid grid-cols-2 gap-3"><input type="number" min="512" max="6144" value={min} onChange={e=>setMin(e.target.value)} className={input}/><input type="number" min="512" max="6144" value={max} onChange={e=>setMax(e.target.value)} className={input}/></div><button onClick={saveRam} className="mt-3 w-full rounded-xl border border-zinc-700 px-4 py-3">Save RAM</button><button onClick={accept} className="mt-3 w-full rounded-xl border border-zinc-700 px-4 py-3">{eula?"EULA accepted":"Accept Minecraft EULA"}</button></Card></div>
{msg&&<p className="text-sm text-emerald-400">{msg}</p>}{error&&<p className="text-sm text-red-400">{error}</p>}</div></main>}
export default function App(){const[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{api("/api/auth/me").then(r=>setUser(r.user)).catch(()=>setUser(null)).finally(()=>setLoading(false))},[]);if(loading)return <div className="min-h-screen bg-zinc-950 p-8 text-zinc-400">Loading…</div>;const path=location.pathname;if(path==="/setup"&&!user)return <Setup onLogin={setUser}/>;if(path==="/login"&&!user)return <Login onLogin={setUser}/>;if(path==="/change-password"&&user)return <ChangePassword user={user} onLogout={()=>setUser(null)}/>;if(!user)return <Login onLogin={setUser}/>;return <Dashboard user={user} onLogout={()=>setUser(null)}/>;}
