import { beforeEach,describe,expect,it,vi } from "vitest";
import { decryptWebhookUrl,encryptWebhookUrl,maskDiscordWebhookUrl,notifyWebhook,validateDiscordWebhookUrl } from "../notifications/webhook.js";
beforeEach(()=>{process.env.WEBHOOK_ENCRYPTION_KEY=Buffer.alloc(32,7).toString("base64");});
describe("Group 10 Discord webhooks",()=>{
 it("accepts valid official Discord webhook URLs",()=>{for(const value of ["https://discord.com/api/webhooks/123/token","https://discordapp.com/api/webhooks/987/another-token"])expect(()=>validateDiscordWebhookUrl(value)).not.toThrow();});
 it("rejects unsafe Discord webhook URLs",()=>{for(const value of ["http://discord.com/api/webhooks/123/token","https://discord.com.evil.com/api/webhooks/123/token","https://evil.com/?x=discord.com","https://user:pass@discord.com/api/webhooks/123/token","https://discord.com:443/api/webhooks/123/token","https://discord.com/api/other/123/token","garbage"])expect(()=>validateDiscordWebhookUrl(value)).toThrow();});
 it("encrypts and decrypts without storing plaintext",()=>{const url="https://discord.com/api/webhooks/123/secret-token";const encrypted=encryptWebhookUrl(url);expect(encrypted).not.toContain("secret-token");expect(decryptWebhookUrl(encrypted)).toBe(url);});
 it("masks webhook URLs",()=>{expect(maskDiscordWebhookUrl("https://discord.com/api/webhooks/123/secret-token")).toBe("https://discord.com/api/webhooks/123/***");});
 it("does not throw when Discord delivery fails",async()=>{const {db}=await import("../database/db.js");db.prepare("UPDATE webhook_settings SET enabled=1,webhook_url_encrypted=? WHERE id=1").run(encryptWebhookUrl("https://discord.com/api/webhooks/123/token"));const fetchMock=vi.spyOn(globalThis,"fetch").mockRejectedValue(new Error("network"));await expect(notifyWebhook("start")).resolves.toBe(false);fetchMock.mockRestore();});
 it("rate limiter blocks after its configured limit",async()=>{const {createWebhookTestLimiter}=await import("../routes/webhooks.js");const express=(await import("express")).default;const supertest=(await import("supertest")).default;const app=express();app.set("trust proxy",false);app.post("/test",createWebhookTestLimiter(2),(_req,res)=>res.json({ok:true}));const request=supertest(app);expect((await request.post("/test")).status).toBe(200);expect((await request.post("/test")).status).toBe(200);expect((await request.post("/test")).status).toBe(429);});
});
